name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-modules-

      - run: npm install
      - run: npm run release

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            build/release/**/*.AppImage

    strategy:
      matrix:
        os: [ubuntu-latest]
